#----------------------------------------------#

spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: console

  application:
    name: BloggingEngineAPI

  datasource:
    url: jdbc:mysql://news_mysql:3306/news_outlet_db
    username: news_outlet
    password: news_outlet
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        hbm2ddl:
          auto: update
      defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  config: classpath:logback-spring.xml

  level:
    root: INFO
    net:
      ttddyy:
        dsproxy:
          listener: DEBUG

server:
  port: 8080

app:
  jwt:
    secret: "f6e9567a0b93eb68a5d331d163494adb14adfa067d148c3c165efa59928dfc95"
    expiration: 900 000 # 15 minutes in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#----------------------------------------------#